name: csharp-client from Outkit
env:
  VERSION_NUMBER: NotSet
on: [push]
jobs:
  job_1:
    runs-on: windows-latest
    steps:  
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
#        dotnet-version: 5.0.100-preview.7

    - name: Setup Nuget.exe (warrenbuckley)
      uses: warrenbuckley/Setup-Nuget@v1
      
    # Add Deps from HMA Nuget Server
    - name: Register GPR
      run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/hmasw/index.json" -UserName ${{ secrets.HMA_NUGET_USERNAME }} -Password ${{ secrets.HMA_NUGET_PASSWORD }}
  
    # Build
    - name: Run build
      run: dotnet build ./Outkit/Outkit.csproj --configuration Release

    # Test
    #- name: Run Tests
    #  run: dotnet test ./Hma.Utils.Tests/calc2tests/hma.utils.calc2.tests.csproj --configuration Release
    #- name: Run Tests
    #  run: dotnet test ./Hma.Utils.Tests/Hma.Utils.Test/Hma.Utils.Test.csproj --configuration Release

    - name: push package
      run: nuget push *\bin\Release\*.nupkg -Source "GPR"
